sudo: required
services:
  - docker

before_install:
  - docker build -t ejazahmeddev/docker-react-travis -f Dockerfile.dev .

script:
  - docker run ejazahmeddev/docker-react-travis npm run test -- --coverage